image:
  - Visual Studio 2017

environment:
  global:
    NAME: nanovg
    ASDF_SYSTEM: bodge-nanovg
  matrix:
  - platform: x64
    TARGET_ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-premake
    BODGE_GL_VERSION: gl3
  - platform: x86
    TARGET_ARCH: i686
    CFLAGS: -m32
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-cmake mingw-w64-i686-premake
    BODGE_GL_VERSION: gl3
  - platform: x64
    TARGET_ARCH: x86_64
    CFLAGS: -m64
    PATH: C:\msys64\mingw64\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-premake
    BODGE_GL_VERSION: gl2
  - platform: x86
    TARGET_ARCH: i686
    CFLAGS: -m32
    PATH: C:\msys64\mingw32\bin\;C:\msys64\usr\bin\;$(PATH)
    PACKAGES: mingw-w64-i686-toolchain mingw-w64-i686-cmake mingw-w64-i686-premake
    BODGE_GL_VERSION: gl2

skip_non_tags: true

branches:
  only:
    - master
    - "/^v\\d+(\\.\\d+)+$/"

install:
  - git submodule update --init --recursive
  - pacman --needed --noconfirm -S zip unzip base-devel %PACKAGES%
  - curl -L http://bodge.borodust.org/files/install.sh | sh

build_script:
  - set TARGET_ARTIFACT=lib%NAME%.dll.%BODGE_GL_VERSION%.bodged-%TARGET_ARCH%-windows-%APPVEYOR_REPO_TAG_NAME%
  - set TARGET_SPEC=%TARGET_ARTIFACT%-spec.zip
  - >
    sh -c "
    export PATH=$HOME/.bodge/bin/:$PATH
    && export APPVEYOR_BUILD_DIR=\"$(cygpath -m '%APPVEYOR_BUILD_FOLDER%')\"
    && BODGE_GL_VERSION=%BODGE_GL_VERSION% CFLAGS=%CFLAGS% TARGET_ARCH=%TARGET_ARCH% cd src/lib/
    && make clean build
    && lisp $APPVEYOR_BUILD_DIR/util/regen-spec
    --arch %TARGET_ARCH% --mode %BODGE_GL_VERSION%
    $APPVEYOR_BUILD_DIR %ASDF_SYSTEM% $APPVEYOR_BUILD_DIR/%TARGET_SPEC%"
  - mv %APPVEYOR_BUILD_FOLDER%\src\lib\lib%NAME%.dll.bodged %APPVEYOR_BUILD_FOLDER%\%TARGET_ARTIFACT%


artifacts:
  - path: $(TARGET_ARTIFACT)
    name: target_artifact
  - path: $(TARGET_SPEC)
    name: target_spec

deploy:
  provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: Z5XWjDOBlCrmfz3SQAjnLKtdgI5B2b/owJhRPNWYGrI+qwVNbBc4cZiroBZReWP7
  artifact: target_artifact, target_spec
  force_update: true
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
